import React from 'react'

export const About = () => {
  return (
    <>
    <h1>About Shoppee</h1>
    <article>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt dolorem eligendi blanditiis asperiores ex ipsum facilis voluptatum nostrum ratione repudiandae doloremque tempora minus quam modi, quo ullam excepturi totam error velit beatae cupiditate? Sit iusto harum, facilis alias eaque, soluta sapiente voluptatem, aperiam porro delectus perferendis. Quia sit qui in voluptatem illo, aliquam ducimus consequuntur itaque rerum, cumque illum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum perferendis quia beatae nobis, porro cupiditate, minima distinctio numquam doloremque neque dolor deleniti cumque! Totam, tenetur harum. Quam molestias sed minima soluta blanditiis vitae earum qui distinctio dignissimos eaque itaque rerum iste exercitationem consequatur odio est laudantium eveniet veritatis, reiciendis quis dolorem illo minus omnis praesentium. Mollitia illo vero sequi possimus aliquam laboriosam recusandae suscipit cumque debitis eius similique culpa explicabo esse enim nesciunt laborum quis nam, exercitationem sit minus vitae nostrum. Nemo quidem exercitationem eos eligendi sapiente atque beatae pariatur molestiae quos veritatis nihil sit illo suscipit, illum ducimus mollitia ipsum in quae itaque, tempore accusantium voluptates! Quia pariatur odio sit voluptates blanditiis soluta cum deserunt facilis! Nulla animi quas quaerat, reprehenderit nam nesciunt, fuga soluta, consequuntur dolorem deserunt maiores. Aspernatur veniam sunt vitae enim ab explicabo neque itaque. Sequi natus quis deleniti earum facere quaerat ullam sit beatae eaque iste quae similique, minus, nulla ex, sapiente suscipit a veritatis velit harum vero. Blanditiis maxime quibusdam fuga, odit aperiam odio corrupti porro natus magnam facere, nisi, vel voluptate. Doloribus ab esse deleniti excepturi fuga dignissimos asperiores eaque, nobis, dolores, consectetur quae. Quo aspernatur assumenda illo? Distinctio veritatis reprehenderit soluta neque?</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur optio vel doloremque eveniet ullam dolore blanditiis quia alias expedita eos, maiores molestias dignissimos! Rem soluta magnam, repellat est in id dicta? Sit similique voluptate numquam deleniti rerum minus natus iure voluptatibus velit quod nisi reiciendis harum tenetur reprehenderit magni accusantium in dignissimos dolores, quis sequi magnam cumque quae provident. Dolor non animi eius harum dolorum unde quia deserunt a laborum iste tempora necessitatibus iusto earum fuga at ea quisquam modi eum, velit numquam. Unde possimus magnam, dolor, sunt facilis ipsum officiis rerum illum consectetur excepturi pariatur distinctio neque non dolore?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi rem eos ea qui, ducimus tenetur animi quas iure, illum hic aliquid nulla magnam praesentium voluptas magni ab nemo sunt quibusdam laudantium! Possimus veritatis, excepturi dicta architecto praesentium sint eveniet libero reprehenderit modi nostrum quasi tenetur exercitationem facilis iste cupiditate quidem repudiandae neque amet dolor. Iusto officia blanditiis reiciendis obcaecati aliquid molestiae ullam! Quos minus soluta ut obcaecati sed itaque odio delectus! Iste, assumenda a. Harum officia soluta voluptatem id error nostrum quae vel corporis corrupti dignissimos. Odit doloremque autem voluptatibus veniam nemo sapiente voluptas suscipit harum culpa. Quasi, veritatis animi.</p>
    </article>
    </>
  )
}
